In [1]:
! pip install folium

In [2]:
import folium

In [32]:
m=folium.Map(location=[37.564214, 127.001699], zoom_start=17, tiles='Open Street Map',popups='서울시청')
m

- location : 중심 좌표를 정할수 있다.
- zoom_start : 0~18까지 범위를 정할수있다.
- tiles : 지도의 모양 (기본으로 사용가능 - Open Street Map, Stamen Terrain, Stamen Toner)
    (api key 필요 - Mapbox bright, Mapbox Control room tiles)

In [3]:
m=folium.Map(location=[35.137922, 129.055628],zoom_start=17,tiles='Open Street Map')
m.save('data/map1.html')
m

In [4]:
m=folium.Map(location=[35.137922, 129.055628],tiles='Stamen Toner')
m

In [5]:
m=folium.Map(location=[35.137922, 129.055628],tiles='Stamen Terrain')
m

In [6]:
folium.Marker([35.137922, 129.055628],popup='부산 중심 위치').add_to(m)
m

In [7]:
tooltip='클릭해주세요'
m=folium.Map(location=[35.137922, 129.055628], zoom_start=17, tiles='Open Street Map')
folium.Marker([35.137922, 129.055628],popup='부산 중심 위치',tooltip=tooltip).add_to(m)
folium.Marker([35.139999, 129.055628],popup='위쪽',tooltip=tooltip).add_to(m)
folium.Marker([35.135000, 129.055628],popup='아래쪽',tooltip=tooltip).add_to(m)
folium.Marker([35.137922, 129.056628],popup='우',tooltip=tooltip).add_to(m)
folium.Marker([35.137922, 129.054628],popup='좌',tooltip=tooltip).add_to(m)
m

In [33]:
m=folium.Map(location=[37.564214, 127.001699], zoom_start=17, tiles='Open Street Map')
folium.Marker([37.564214, 127.001699],popup='서울 시청').add_to(m)
m

In [8]:
m=folium.Map(location=[37.564214, 127.001699], zoom_start=17, tiles='Open Street Map')
folium.Marker([37.564214, 127.001699],popup='서울 시청',icon=folium.Icon(color='red',icon='info-sign') ,tooltip='뭘봐').add_to(m)
folium.CircleMarker([37.56583, 126.97472],radius=100,color="#3186cc",fill_color='#cc8631', popup='덕수궁').add_to(m)
m

In [9]:
tooltip='클릭해주세요'
m=folium.Map(location=[35.137922, 129.055628], zoom_start=17, tiles='Stamen Toner')
folium.Marker([35.137922, 129.055628],icon=folium.Icon(icon='star',color='green',icon_color='yellow'),popup='부산 중심 위치',tooltip=tooltip).add_to(m)
folium.Marker([35.139999, 129.055628],icon=folium.Icon(icon='cloud'),popup='위쪽',tooltip=tooltip).add_to(m)
folium.Marker([35.135000, 129.055628],icon=folium.Icon(icon='info-sign',color='red'),popup='아래쪽',tooltip=tooltip).add_to(m)
folium.Marker([35.137922, 129.056628],popup='우',tooltip=tooltip).add_to(m)
folium.Marker([35.137922, 129.054628],popup='좌',tooltip=tooltip).add_to(m)
m

In [10]:
help(folium.Icon)

Help on class Icon in module folium.map:

class Icon(branca.element.MacroElement)
 |  Icon(color='blue', icon_color='white', icon='info-sign', angle=0, prefix='glyphicon', **kwargs)
 |  
 |  Creates an Icon object that will be rendered
 |  using Leaflet.awesome-markers.
 |  
 |  Parameters
 |  ----------
 |  color : str, default 'blue'
 |      The color of the marker. You can use:
 |  
 |          ['red', 'blue', 'green', 'purple', 'orange', 'darkred',
 |           'lightred', 'beige', 'darkblue', 'darkgreen', 'cadetblue',
 |           'darkpurple', 'white', 'pink', 'lightblue', 'lightgreen',
 |           'gray', 'black', 'lightgray']
 |  
 |  icon_color : str, default 'white'
 |      The color of the drawing on the marker. You can use colors above,
 |      or an html color code.
 |  icon : str, default 'info-sign'
 |      The name of the marker sign.
 |      See Font-Awesome website to choose yours.
 |      Warning : depending on the icon you choose you may need to adapt
 |      the `

In [11]:
tooltip='클릭해주세요'
m=folium.Map(location=[35.137922, 129.055628], zoom_start=15, tiles='Open Street Map')
folium.Marker([35.137922, 129.055628],icon=folium.Icon(icon='home',color='red',icon_color='yellow'),popup='부산 중심 위치',tooltip=tooltip).add_to(m)
folium.Marker([35.139999, 129.055628],icon=folium.Icon(icon='star',color='gray'),popup='위쪽',tooltip=tooltip).add_to(m)
folium.Marker([35.135000, 129.055628],icon=folium.Icon(icon='glass',color='green'),popup='아래쪽',tooltip=tooltip).add_to(m)
folium.Marker([35.137922, 129.056628],popup='우',tooltip=tooltip).add_to(m)
folium.Marker([35.137922, 129.054628],popup='좌',tooltip=tooltip).add_to(m)
m

In [12]:
m.add_child(folium.ClickForMarker(popup='클릭마크'))
m

In [13]:
m.add_child(folium.LatLngPopup())
m

In [14]:
from folium import plugins
import os
import numpy as np
import random

In [15]:
N=100
data=np.array(
    [np.random.uniform(low=35, high=38, size=N),
     np.random.uniform(low=126, high=129, size=N)]
).T
data

array([[ 35.23039326, 128.54737677],
       [ 35.77242517, 126.48673253],
       [ 36.26335903, 127.59403766],
       [ 37.95311557, 126.31471178],
       [ 37.58510881, 128.79228825],
       [ 37.80058699, 128.07304442],
       [ 35.72326892, 127.45638519],
       [ 35.36655515, 126.71603317],
       [ 35.33134768, 127.42613548],
       [ 36.69177819, 127.12035899],
       [ 35.59784498, 128.24208636],
       [ 36.04371501, 126.48495276],
       [ 36.63831566, 128.15498288],
       [ 37.69771272, 128.86048267],
       [ 37.73220498, 128.92799709],
       [ 35.06136367, 127.50785074],
       [ 35.82377905, 127.00068745],
       [ 37.36253525, 126.06469208],
       [ 35.71191514, 128.94902543],
       [ 37.55624107, 127.1716063 ],
       [ 35.21063829, 126.70957408],
       [ 36.95984013, 127.33395499],
       [ 35.74798589, 128.7602784 ],
       [ 37.81965979, 128.45667473],
       [ 36.24946358, 127.55052997],
       [ 37.92384396, 128.30436376],
       [ 35.69621942, 126.45807451],
 

In [16]:
popups=[str(i+1) for i in range(N)]
m=folium.Map(location=[37.564214, 127.001699],zoom_start=7)
plugins.MarkerCluster(data,popups=popups).add_to(m)
m.save(os.path.join('data','plugins_1.html'))
m

In [17]:
import pandas as pd

In [18]:
cctv=pd.read_csv('data/CCTV_20190917.csv')
cctv

관리기관명                 소재지도로명주소                소재지지번주소 설치목적구분  카메라대수  \
0   부산광역시 부산진구청       부산광역시 부산진구 성지로 116   부산광역시 부산진구 초읍동 178-6  어린이보호      1   
1   부산광역시 부산진구청    부산광역시 부산진구 안창로14번길 78    부산광역시 부산진구 범천동 1536  어린이보호      0   
2   부산광역시 부산진구청  부산광역시 부산진구 백양대로260번길 16   부산광역시 부산진구 개금동 419-3  어린이보호      0   
3   부산광역시 부산진구청    부산광역시 부산진구 양지로11번길 64   부산광역시 부산진구 양정동 345-2  어린이보호      1   
4   부산광역시 부산진구청     부산광역시 부산진구 국악로60번길 4  부산광역시 부산진구 초읍동 616-15  어린이보호      0   
..          ...                      ...                    ...    ...    ...   
84  부산광역시 부산진구청  부산광역시 부산진구 진사로61번길 28-7   부산광역시 부산진구 개금동 630-5  어린이보호      1   
85  부산광역시 부산진구청        부산광역시 부산진구 복지로 71  부산광역시 부산진구 개금동 565-14  어린이보호      0   
86  부산광역시 부산진구청   부산광역시 부산진구 성지로104번길 26     부산광역시 부산진구 초읍동 540  어린이보호      1   
87  부산광역시 부산진구청  부산광역시 부산진구 백양대로320번길 40  부산광역시 부산진구 개금동 446-14  어린이보호      1   
88  부산광역시 부산진구청   부산광역시 부산진구 백양순환로 70-11   부산광역시 부산진구 당감동 775-2  어린이보호      1   

    카메라화소수    촬영방면정보  보관일수  설치년월      관리기관전화번호         위도          경도  \
0    200.0  360도 전방면  30.0   NaN  051-605-4647  35.180330  129.051626   
1      NaN       NaN   NaN   NaN  051-605-4647  35.146126  129.043400   
2      NaN       NaN   NaN   NaN  051-605-4647  35.156511  129.022270   
3    200.0  360도 전방면  30.0   NaN  051-605-4647  35.171487  129.071727   
4      NaN       NaN   NaN   NaN  051-605-4647  35.174720  129.050461   
..     ...       ...   ...   ...           ...        ...         ...   
84   200.0  360도 전방면  30.0   NaN  051-605-4647  35.145796  129.019467   
85     NaN       NaN   NaN   NaN  051-605-4647  35.147113  129.018426   
86   200.0  360도 전방면  30.0   NaN  051-605-4647  35.180253  129.054447   
87   200.0  360도 전방면  30.0   NaN  051-605-4647  35.156259  129.015978   
88   200.0  360도 전방면  30.0   NaN  051-605-4647  35.168584  129.037950   

       데이터기준일자  
0   2019-09-17  
1   2019-09-17  
2   2019-09-17  
3   2019-09-17  
4   2019-09-17  
..         ...  
84  2019-09-17  
85  2019-09-17  
86  2019-09-17  
87  2019-09-17  
88  2019-09-17  

[89 rows x 13 columns]

In [19]:
popups=list(cctv.iloc[:,1])
popups

['부산광역시 부산진구 성지로 116',
 '부산광역시 부산진구 안창로14번길 78',
 '부산광역시 부산진구 백양대로260번길 16',
 '부산광역시 부산진구 양지로11번길 64',
 '부산광역시 부산진구 국악로60번길 4',
 '부산광역시 부산진구 거제대로 37',
 '부산광역시 부산진구 당감로 79',
 '부산광역시 부산진구 성지로14번길 65',
 '부산광역시 부산진구 백양대로208번길 174',
 '부산광역시 부산진구 개금본동로9번길 41',
 '부산광역시 부산진구 당감서로 16',
 '부산광역시 부산진구 백양관문로77번길 33',
 '부산광역시 부산진구 거제천로40번길 31',
 '부산광역시 부산진구 복지로 117-12',
 '부산광역시 부산진구 백양대로136번길 90',
 '부산광역시 부산진구 연수로11번길 34',
 '부산광역시 부산진구 백양대로136번길 37-9',
 '부산광역시 부산진구 동평로39번길 106',
 '부산광역시 부산진구 엄광로386번길 24',
 '부산광역시 부산진구 냉정로178번길 13',
 '부산광역시 부산진구 백양관문로 25-29',
 '부산광역시 부산진구 화지로 6',
 '부산광역시 부산진구 당감서로 120',
 '부산광역시 부산진구 백양관문로 112',
 '부산광역시 부산진구 복지로 70',
 '부산광역시 부산진구 성지로74번길 60',
 '부산광역시 부산진구 백양순환로18번길 36',
 '부산광역시 부산진구 당감로 22-5',
 '부산광역시 부산진구 당감서로100번길 56',
 '부산광역시 부산진구 동성로 26',
 '부산광역시 부산진구 당감로64번길 27',
 '부산광역시 부산진구 경마장로5번길 71',
 '부산광역시 부산진구 엄광로 122',
 '부산광역시 부산진구 진남로 506',
 '부산광역시 부산진구 범천로 30',
 '부산광역시 부산진구 새싹로14번길 7',
 '부산광역시 부산진구 엄광로182번길 15-14',
 '부산광역시 부산진구 성지로46번길 15',
 '부산광역시 부산진구 동평로183번길 114',


In [20]:
counts=list(cctv.iloc[:,4])
counts

[1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 5,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 2,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 0,
 1,
 1,
 1]

In [21]:
lats=list(cctv.iloc[:,10])
longs=list(cctv.iloc[:,11])

lat_longs=np.array([lats,longs]).T
lat_longs

array([[ 35.1803305, 129.0516257],
       [ 35.1461264, 129.0434004],
       [ 35.1565111, 129.0222699],
       [ 35.1714866, 129.0717271],
       [ 35.1747205, 129.0504611],
       [ 35.1720901, 129.0655534],
       [ 35.1689816, 129.0375669],
       [ 35.1733928, 129.0586357],
       [ 35.1635902, 129.0244649],
       [ 35.1571185, 129.0235693],
       [ 35.1623331, 129.0366197],
       [ 35.1644943, 129.0277604],
       [ 35.1792288, 129.0727223],
       [ 35.1426032, 129.0195381],
       [ 35.1639901, 129.0338286],
       [ 35.1747949, 129.0737388],
       [ 35.1618761, 129.0332321],
       [ 35.1676615, 129.0292801],
       [ 35.1514439, 129.0459936],
       [ 35.1492985, 129.0196731],
       [ 35.1608238, 129.0294651],
       [ 35.1755761, 129.0640828],
       [ 35.1692452, 129.0336184],
       [ 35.1684981, 129.0283234],
       [ 35.1475527, 129.0192145],
       [ 35.1790061, 129.0563305],
       [ 35.1662387, 129.0352533],
       [ 35.1643376, 129.0408295],
       [ 35.1703418,

In [22]:
print(len(popups),len(counts),lat_longs.shape)

89 89 (89, 2)


In [23]:
popups1, lat_longs1=[],[]
for i in range(len(counts)):
    if counts[i]>0:
        popups1.append(popups[i])
        lat_longs1.append(lat_longs[i])
print(len(popups1), len(lat_longs1))

lat_longs_arr=np.array(lat_longs1)
lat_longs_arr

70 70


array([[ 35.1803305, 129.0516257],
       [ 35.1714866, 129.0717271],
       [ 35.1635902, 129.0244649],
       [ 35.1571185, 129.0235693],
       [ 35.1623331, 129.0366197],
       [ 35.1644943, 129.0277604],
       [ 35.1792288, 129.0727223],
       [ 35.1426032, 129.0195381],
       [ 35.1639901, 129.0338286],
       [ 35.1747949, 129.0737388],
       [ 35.1618761, 129.0332321],
       [ 35.1676615, 129.0292801],
       [ 35.1492985, 129.0196731],
       [ 35.1608238, 129.0294651],
       [ 35.1755761, 129.0640828],
       [ 35.1692452, 129.0336184],
       [ 35.1475527, 129.0192145],
       [ 35.1662387, 129.0352533],
       [ 35.1703418, 129.0338837],
       [ 35.1679636, 129.0401347],
       [ 35.1707573, 129.0632483],
       [ 35.1466982, 129.0255141],
       [ 35.1499601, 129.0560701],
       [ 35.1597736, 129.0581321],
       [ 35.1749851, 129.0557922],
       [ 35.1661393, 129.0515033],
       [ 35.1497283, 129.0522612],
       [ 35.1715531, 129.0328583],
       [ 35.1639901,

In [24]:

m=folium.Map(location=lat_longs_arr[0],zoom_start=15)
plugins.MarkerCluster(lat_longs_arr,popups=popups1).add_to(m)
m.save(os.path.join('data','cctv01.html'))
m

# 버스위치정보 지도 시각화
- 공공데이터 활용신청
- 서울특별시 버스노선정보조회 서비스
- 서울특별시 버스위치정보조회 서비스

In [25]:
from bs4 import BeautifulSoup as bs
import urllib.request as req

In [26]:
busNum=504
key='bz6p9J0zjOTIbSrGsm6BH3B4i9IEW29rnGC6LNchn750ZVUpKW3HKr211MoqBZhOy02OyMRxsN60JqwPc0KpXQ=='
url='http://ws.bus.go.kr/api/rest/busRouteInfo/getBusRouteList?serviceKey=%s&strSrch=%s'%(key,busNum)
savename='data/businfo.xml'
req.urlretrieve(url, savename)

('data/businfo.xml', <http.client.HTTPMessage at 0x16e1eade410>)

In [27]:
xml=open(savename, 'r', encoding='utf-8').read()
soup=bs(xml,'xml')
item_list=soup.find_all('itemList')
busRoute_id=''
for item in item_list:
    busRouteId=item.find('busRouteId').text
    busRoutNm=item.find('busRouteNm').text

    if busRoutNm.strip()==str(busNum):
        print(busRouteId,busRoutNm)
        busRoute_id=busRouteId
print(busRoute_id)


100100079 504
100100079


In [28]:
url='http://ws.bus.go.kr/api/rest/buspos/getBusPosByRtid?serviceKey=%s&busRouteId=%s'%(key,busRoute_id)
savename='data/buspos.xml'
req.urlretrieve(url,savename)

('data/buspos.xml', <http.client.HTTPMessage at 0x16e1ea41000>)

In [29]:
xml=open(savename, 'r',encoding='utf-8').read()
soup=bs(xml,'xml')
busPos=[]
plainNos=[]
item_list=soup.find_all('itemList')
for item in item_list:
    plainNo=item.find('plainNo').text
    gpsX=item.find('gpsX').text
    gpsY=item.find('gpsY').text
    plainNos.append(str(plainNo))
    busPos.append([float(gpsY),float(gpsX)])
print(busPos)
print(plainNos)


[[37.46124, 126.875262], [37.476095, 126.86521], [37.475888, 126.881321], [37.478789, 126.898246], [37.479338, 126.901805], [37.484154, 126.929748], [37.494514, 126.927398], [37.507245, 126.94008], [37.512537, 126.952959], [37.52219, 126.961795], [37.535013, 126.973624], [37.55037, 126.971969], [37.561829, 126.981318], [37.55783, 126.973029], [37.54407, 126.972139], [37.532335, 126.970659], [37.526301, 126.96495], [37.512646, 126.952627], [37.51365, 126.94037], [37.501325, 126.933117], [37.489985, 126.927551], [37.480563, 126.907368], [37.479314, 126.890552], [37.475721, 126.880401], [37.480739, 126.868242], [37.479394, 126.863778], [37.478893, 126.863738], [37.474873, 126.866508], [37.467682, 126.868615], [37.463018, 126.872433]]
['서울74사1561', '서울71사1208', '서울74사8752', '서울74사5417', '서울74사8838', '서울74사3385', '서울74사8830', '서울74사5412', '서울74사8835', '서울74사3384', '서울74사8731', '서울74사8991', '서울74사8953', '서울74사7026', '서울71사1205', '서울74사5419', '서울74사9929', '서울74사5415', '서울74사7035', '서울74사5006'

In [30]:
m=folium.Map(location=busPos[0],zoom_start=15)
plugins.MarkerCluster(busPos,popups=plainNos).add_to(m)
m.save(os.path.join('data','bus01.html'))
m