In [1]:
import torch

In [4]:
t1=torch.tensor([[1,2],[3,4]])
# t2=torch.tensor([[1,2],[3,4]], device='cuda:0')
t3=torch.tensor([[1,2],[3,4]], dtype=torch.float64)
print(t1)
# print(t2)
print(t3)

tensor([[1, 2],
        [3, 4]])
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [6]:
t4=torch.FloatTensor([[1,2],[3,4]])
t5=torch.LongTensor([[1,2],[3,4]])
t6=torch.ByteTensor([[1,2],[3,4]])
print(t4)
print(t5)
print(t6)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], dtype=torch.uint8)


In [7]:
import numpy as np
x=np.array([[1,2],[3,4]])
print(x)
print(type(x))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


In [8]:
t=torch.from_numpy(x)
print(t, type(t))

tensor([[1, 2],
        [3, 4]], dtype=torch.int32) <class 'torch.Tensor'>


In [9]:
nx=t.numpy()
print(nx, type(nx))


[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [18]:
ft=torch.FloatTensor([[1,2,3],[4,5,6]])
print(ft)
lt=ft.long()
print(lt)
bt=ft.byte()
print(bt)
ft1=lt.float()
print(ft1)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.uint8)
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [29]:
x=torch.tensor([[[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]]])
print(x)

tensor([[[[ 1,  2],
          [ 3,  4],
          [ 5,  6]],

         [[ 7,  8],
          [ 9, 10],
          [11, 12]]]])


In [30]:
print(x.size())
print(x.shape)
print(x.dim())
print(x.size(0))
print(x.shape[0])
print(x.size(1))
print(x.shape[1])
print(x.size(2))
print(x.shape[-1])


torch.Size([1, 2, 3, 2])
torch.Size([1, 2, 3, 2])
4
1
1
2
2
3
2


In [38]:
a=torch.FloatTensor([[1,2],[3,4]])
b=torch.FloatTensor([[2,2],[4,4]])
print(a)
print(b)

tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 2.],
        [4., 4.]])


In [34]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a==b)
print(a!=b)
print(a**b)

tensor([[3., 4.],
        [7., 8.]])
tensor([[-1.,  0.],
        [-1.,  0.]])
tensor([[ 2.,  4.],
        [12., 16.]])
tensor([[0.5000, 1.0000],
        [0.7500, 1.0000]])
tensor([[False,  True],
        [False,  True]])
tensor([[ True, False],
        [ True, False]])
tensor([[  1.,   4.],
        [ 81., 256.]])


In [37]:
print(a)
print(a.mul(b))
print(a)
print(a.mul_(b))
print(a)

tensor([[1., 2.],
        [3., 4.]])
tensor([[ 2.,  4.],
        [12., 16.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[ 2.,  4.],
        [12., 16.]])
tensor([[ 2.,  4.],
        [12., 16.]])


In [42]:
x=a
print(x)
print(x.sum())
print(x.sum(dim=0))
print(x.sum(dim=1))
print(x.mean())
print(x.mean(dim=0))
print(x.mean(dim=1))

tensor([[1., 2.],
        [3., 4.]])
tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])


In [45]:
y=1
z=x+y
print(z)
print(z.size())

tensor([[2., 3.],
        [4., 5.]])
torch.Size([2, 2])


In [47]:
y=torch.FloatTensor([3,4])
print(y.size())
z=x+y
print(z)
print(z.size())

torch.Size([2])
tensor([[4., 6.],
        [6., 8.]])
torch.Size([2, 2])


In [51]:
x=torch.FloatTensor([[1,2]])
y=torch.FloatTensor([[3],[4]])
print(x.size())
print(y.size())
z=x+y
print(z)
print(z.size())

torch.Size([1, 2])
torch.Size([2, 1])
tensor([[4., 5.],
        [5., 6.]])
torch.Size([2, 2])


In [55]:
a=np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
x=torch.FloatTensor([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
y=torch.FloatTensor([1,2,3,4,5,6,7,8,9,10,11,12])
print(x)
print(x.size())
print(y.size)

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])
torch.Size([3, 2, 2])
<built-in method size of Tensor object at 0x000001E7AE253D30>


In [60]:
print(x.view(3,4))
print(y.view(3,4))
print(y.view(2,3,2))

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.]],

        [[ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]])


In [66]:
# squeeze : 텐서에서 차원이 1인 차원을 제거
y=y.view(3,1,4)
print(y.squeeze())
print(y.squeeze().size())
print(y.squeeze(0).size()) # 차원이 1인 차원 제거(x)
print(y.squeeze(1).size())# 차원이 1인 차원 제거(o)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
torch.Size([3, 4])
torch.Size([3, 1, 4])
torch.Size([3, 4])


In [75]:
x=torch.FloatTensor([[1,2],[3,4]])
print(x)
print(x.size())
print(x.unsqueeze(2))
print(x.unsqueeze(1))#[2,1,2]
print(x.unsqueeze(2).size()) #[2,2,1]
print(x.unsqueeze(-1)) #[2,2,1]
print(x.reshape(2,2,1))#[2,2,1]

tensor([[1., 2.],
        [3., 4.]])
torch.Size([2, 2])
tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])
tensor([[[1., 2.]],

        [[3., 4.]]])
torch.Size([2, 2, 1])
tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])
tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])


In [78]:
x=y.view(3,2,2)
print(x)
print(x[0])
print(x[0,:])
print(x[0,:,:])
print(x[-1])
print(x[-1,:])
print(x[-1,:,:])
print(x[:,0,:])
print(x[1:3,:,:].size())
print(x[:,:1,:].size())
print(x[:,:-1,:].size())

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[ 9., 10.],
        [11., 12.]])
tensor([[ 9., 10.],
        [11., 12.]])
tensor([[ 9., 10.],
        [11., 12.]])
tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]])
torch.Size([2, 2, 2])
torch.Size([3, 1, 2])
torch.Size([3, 1, 2])


In [89]:
x=torch.randperm(40)
x=x.view(10,-1)
print(x)
print(x.size())
split=x.split(4, dim=0)
for s in split:
    print(s.size())

tensor([[14, 22, 36, 37],
        [ 8,  9,  5, 25],
        [ 0, 10, 20,  7],
        [ 3, 23, 30, 39],
        [38, 15, 19, 27],
        [28, 11, 26, 32],
        [ 1, 35, 13, 24],
        [17,  6,  2,  4],
        [18, 33, 29, 34],
        [31, 12, 21, 16]])
torch.Size([10, 4])
torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([2, 4])


In [93]:
chunks=x.chunk(2, dim=0)
print(chunks)
for c in chunks:
    print(c.size())

(tensor([[14, 22, 36, 37],
        [ 8,  9,  5, 25],
        [ 0, 10, 20,  7],
        [ 3, 23, 30, 39],
        [38, 15, 19, 27]]), tensor([[28, 11, 26, 32],
        [ 1, 35, 13, 24],
        [17,  6,  2,  4],
        [18, 33, 29, 34],
        [31, 12, 21, 16]]))
torch.Size([5, 4])
torch.Size([5, 4])


In [94]:
print(x.size())

torch.Size([10, 4])


In [95]:
x=torch.FloatTensor([[[1,1],[2,2]],[[3,3],[4,4]],[[5,5],[6,6]]])
print(x.size())

torch.Size([3, 2, 2])


In [97]:
indice=torch.LongTensor([0,2])

y=x.index_select(dim=0, index=indice)
print(y)

tensor([[[1., 1.],
         [2., 2.]],

        [[5., 5.],
         [6., 6.]]])


In [99]:
x=torch.FloatTensor([[1,2,3],[4,5,6],[7,8,9]])
y=torch.FloatTensor([[11,12,13],[14,15,16],[17,18,19]])
z=torch.cat([x,y], dim=0)
print(z)
print(z.size())
z1=torch.cat([x,y], dim=-1)
print(z1)
print(z1.size())

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [11., 12., 13.],
        [14., 15., 16.],
        [17., 18., 19.]])
torch.Size([6, 3])
tensor([[ 1.,  2.,  3., 11., 12., 13.],
        [ 4.,  5.,  6., 14., 15., 16.],
        [ 7.,  8.,  9., 17., 18., 19.]])
torch.Size([3, 6])


In [104]:
a=np.arange(1,13)
x=torch.from_numpy(a).view(3,1,4)
y=x.expand(3,2,4)
print(x)
print(y)

tensor([[[ 1,  2,  3,  4]],

        [[ 5,  6,  7,  8]],

        [[ 9, 10, 11, 12]]], dtype=torch.int32)
tensor([[[ 1,  2,  3,  4],
         [ 1,  2,  3,  4]],

        [[ 5,  6,  7,  8],
         [ 5,  6,  7,  8]],

        [[ 9, 10, 11, 12],
         [ 9, 10, 11, 12]]], dtype=torch.int32)


In [107]:
x=torch.randperm(3**3).view(3,3,-1)
print(x)

tensor([[[26, 25,  2],
         [ 5, 24,  9],
         [ 1, 19,  8]],

        [[12, 13,  7],
         [10, 20, 16],
         [ 6, 15,  3]],

        [[21,  4, 11],
         [18, 14, 22],
         [ 0, 17, 23]]])


In [109]:
y=x.argmax(dim=0)
print(y)

tensor([[0, 0, 2],
        [2, 0, 2],
        [1, 0, 2]])


In [110]:
y=x.argmax(dim=1)
print(y)

tensor([[0, 0, 1],
        [0, 1, 1],
        [0, 2, 2]])


In [111]:
y=x.argmax(dim=-1)
print(y)

tensor([[0, 1, 1],
        [1, 1, 1],
        [0, 2, 2]])


In [112]:
x

tensor([[[26, 25,  2],
         [ 5, 24,  9],
         [ 1, 19,  8]],

        [[12, 13,  7],
         [10, 20, 16],
         [ 6, 15,  3]],

        [[21,  4, 11],
         [18, 14, 22],
         [ 0, 17, 23]]])

In [117]:
values, indices=torch.topk(x,k=3, dim=-1)
print(values)
print(indices)

tensor([[[26, 25,  2],
         [24,  9,  5],
         [19,  8,  1]],

        [[13, 12,  7],
         [20, 16, 10],
         [15,  6,  3]],

        [[21, 11,  4],
         [22, 18, 14],
         [23, 17,  0]]])
tensor([[[0, 1, 2],
         [1, 2, 0],
         [1, 2, 0]],

        [[1, 0, 2],
         [1, 2, 0],
         [1, 0, 2]],

        [[0, 2, 1],
         [2, 0, 1],
         [2, 1, 0]]])


In [122]:
x=torch.FloatTensor([i+1 for i in range(3**2)]).view(3,-1)
print(x)
mask=x>4
print(mask)
y=x.masked_fill(mask, value=100)
print(y)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
tensor([[False, False, False],
        [False,  True,  True],
        [ True,  True,  True]])
tensor([[  1.,   2.,   3.],
        [  4., 100., 100.],
        [100., 100., 100.]])


In [127]:
print(torch.ones(2,3))
print(torch.zeros(2,3))

print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
