In [19]:
import torch
import torch.optim as optim

In [20]:
x1_train = torch.FloatTensor([[73],[93],[89],[96],[73]])
x2_train = torch.FloatTensor([[80],[88],[91],[98],[66]])
x3_train = torch.FloatTensor([[75],[93],[90],[100],[70]])
y_train = torch.FloatTensor([[152],[185],[180],[196],[142]])

In [21]:
w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [22]:
optimizer=optim.SGD([w1,w2,w3,b], lr=1e-5)
nb_epochs=100000

for epcho in range(nb_epochs):
    hypothesis=x1_train*w1+x2_train*w2 +x3_train*w3+b

    cost=torch.mean((hypothesis-y_train)**2)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epcho%400==0:
        print('Epoch=',epcho,'w1=',w1.item(),'w2=',w2.item(),'w3=',w3.item(),'b=',b.item(),'cost=',cost.item())

Epoch= 0 w1= 0.29401201009750366 w2= 0.2935999929904938 w3= 0.2973800003528595 b= 0.0034199999645352364 cost= 29661.80078125
Epoch= 400 w1= 0.6894262433052063 w2= 0.6434438228607178 w3= 0.6777952909469604 b= 0.00836699828505516 cost= 1.375730276107788
Epoch= 800 w1= 0.7088890075683594 w2= 0.622265636920929 w3= 0.6794635057449341 b= 0.008947668597102165 cost= 1.1678179502487183
Epoch= 1200 w1= 0.7265268564224243 w2= 0.6033490300178528 w3= 0.6807023882865906 b= 0.009511923417448997 cost= 0.999893844127655
Epoch= 1600 w1= 0.7425243258476257 w2= 0.5864613652229309 w3= 0.6815593838691711 b= 0.010061148554086685 cost= 0.8641611337661743
Epoch= 2000 w1= 0.7570484280586243 w2= 0.5713934898376465 w3= 0.6820759177207947 b= 0.01059654913842678 cost= 0.7543893456459045
Epoch= 2400 w1= 0.7702491283416748 w2= 0.5579580664634705 w3= 0.6822887063026428 b= 0.011119304224848747 cost= 0.6654970645904541
Epoch= 2800 w1= 0.7822605967521667 w2= 0.5459862947463989 w3= 0.6822317242622375 b= 0.0116303777322173

In [23]:
x_train = torch.FloatTensor([[73,80,75],[93,88,93],[89,91,80],[96,98,100],[73,66,70]])
y_train = torch.FloatTensor([[152],[185],[180],[196],[142]])

In [24]:
W=torch.zeros((3,1), requires_grad=True)
b=torch.zeros(1,requires_grad=True)

optimizer=optim.SGD([W,b], lr=1e-5)

nb_epochs=2000

for epcho in range(nb_epochs):
    hypothesis=x_train.matmul(W)+b
    
    
    cost=torch.mean((hypothesis-y_train)**2)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print("epoch=",epcho, "hypothesis=",hypothesis.squeeze().detach(),"cost=",cost.item())


epoch= 0 hypothesis= tensor([0., 0., 0., 0., 0.]) cost= 29661.80078125
epoch= 1 hypothesis= tensor([66.7178, 80.1701, 76.1025, 86.0194, 61.1565]) cost= 9537.6943359375
epoch= 2 hypothesis= tensor([104.5421, 125.6208, 119.2478, 134.7862,  95.8280]) cost= 3069.590087890625
epoch= 3 hypothesis= tensor([125.9858, 151.3882, 143.7087, 162.4333, 115.4844]) cost= 990.6708984375
epoch= 4 hypothesis= tensor([138.1429, 165.9963, 157.5768, 178.1071, 126.6283]) cost= 322.4820861816406
epoch= 5 hypothesis= tensor([145.0350, 174.2780, 165.4395, 186.9928, 132.9461]) cost= 107.7170639038086
epoch= 6 hypothesis= tensor([148.9423, 178.9730, 169.8976, 192.0301, 136.5279]) cost= 38.687496185302734
epoch= 7 hypothesis= tensor([151.1574, 181.6346, 172.4254, 194.8856, 138.5585]) cost= 16.499042510986328
epoch= 8 hypothesis= tensor([152.4131, 183.1435, 173.8590, 196.5043, 139.7097]) cost= 9.365655899047852
epoch= 9 hypothesis= tensor([153.1250, 183.9988, 174.6723, 197.4217, 140.3625]) cost= 7.071113586425781
e

In [25]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)
x_train=torch.FloatTensor([[1],[2],[3]])
y_train=torch.FloatTensor([[2],[4],[6]])

In [26]:
model=nn.Linear(1,1)
print(list(model.parameters()))

optimizer=torch.optim.SGD(model.parameters(),lr=1e-5)

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [27]:
nb_epochs=2000

for epcho in range(nb_epochs):
    prediction=model(x_train)
    cost=F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epcho % 100==0:
        print("epcho=",epcho,"cost=",cost.item())

epcho= 0 cost= 13.103541374206543
epcho= 100 cost= 12.816107749938965
epcho= 200 cost= 12.534987449645996
epcho= 300 cost= 12.260029792785645
epcho= 400 cost= 11.991106986999512
epcho= 500 cost= 11.7280855178833
epcho= 600 cost= 11.47083568572998
epcho= 700 cost= 11.219229698181152
epcho= 800 cost= 10.973143577575684
epcho= 900 cost= 10.732457160949707
epcho= 1000 cost= 10.497054100036621
epcho= 1100 cost= 10.266816139221191
epcho= 1200 cost= 10.041630744934082
epcho= 1300 cost= 9.821383476257324
epcho= 1400 cost= 9.605978965759277
epcho= 1500 cost= 9.39529037475586
epcho= 1600 cost= 9.189227104187012
epcho= 1700 cost= 8.987686157226562
epcho= 1800 cost= 8.790568351745605
epcho= 1900 cost= 8.597773551940918


In [28]:
new_data=torch.FloatTensor([[4.0]])

pred_y=model(new_data)
print("예측값:",pred_y)

예측값: tensor([[2.8631]], grad_fn=<AddmmBackward0>)


# nn.Modual 사용 Mul_regression 구현

In [29]:
x_train = torch.FloatTensor([[73,80,75],[93,88,93],[89,91,80],[96,98,100],[73,66,70]])
y_train = torch.FloatTensor([[152],[185],[180],[196],[142]])

In [30]:
model=nn.Linear(3,1)
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.1119,  0.2710, -0.5435]], requires_grad=True), Parameter containing:
tensor([0.3462], requires_grad=True)]


In [32]:
optimizer=torch.optim.SGD(model.parameters(),lr=1e-5)
nb_epochs=10000

for epcho in range(nb_epochs):
    prediction=model(x_train)
    cost=F.mse_loss(prediction, y_train)

    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epcho % 400==0:
        print("epcho=",epcho,"cost=",cost.item())

epcho= 0 cost= 41675.6171875
epcho= 400 cost= 4.510687351226807
epcho= 800 cost= 3.7279677391052246
epcho= 1200 cost= 3.100285291671753
epcho= 1600 cost= 2.5939269065856934
epcho= 2000 cost= 2.1830406188964844
epcho= 2400 cost= 1.8477424383163452
epcho= 2800 cost= 1.5726631879806519
epcho= 3200 cost= 1.3458383083343506
epcho= 3600 cost= 1.1579153537750244
epcho= 4000 cost= 1.0015246868133545
epcho= 4400 cost= 0.8708316683769226
epcho= 4800 cost= 0.7612025737762451
epcho= 5200 cost= 0.6689440011978149
epcho= 5600 cost= 0.591052770614624
epcho= 6000 cost= 0.5251280069351196
epcho= 6400 cost= 0.46917518973350525
epcho= 6800 cost= 0.42159709334373474
epcho= 7200 cost= 0.3810548186302185
epcho= 7600 cost= 0.34645694494247437
epcho= 8000 cost= 0.31687894463539124
epcho= 8400 cost= 0.29157254099845886
epcho= 8800 cost= 0.2698829770088196
epcho= 9200 cost= 0.2512804865837097
epcho= 9600 cost= 0.23532333970069885


In [33]:
new_data=torch.FloatTensor([[73,80,75]])
pred_y=model(new_data)
print("예측값:",pred_y)

예측값: tensor([[152.7641]], grad_fn=<AddmmBackward0>)


# 단순선형회귀 클래스로 구현

In [34]:
torch.manual_seed(1)
x_train=torch.FloatTensor([[1],[2],[3]])
y_train=torch.FloatTensor([[2],[4],[6]])

In [36]:
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear=nn.Linear(1,1)

    def forward(self,x):
        return self.linear(x)

In [37]:
model=LinearRegressionModel()
optimizer=torch.optim.SGD(model.parameters(),lr=0.01)

nb_epochs=2000

for epcho in range(nb_epochs):
    prediction=model(x_train)

    cost=F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epcho % 100==0:
        print("epcho=",epcho,"cost=",cost.item())

epcho= 0 cost= 13.103541374206543
epcho= 100 cost= 0.00279058120213449
epcho= 200 cost= 0.00172441138420254
epcho= 300 cost= 0.0010655784280970693
epcho= 400 cost= 0.0006584661896340549
epcho= 500 cost= 0.0004068926500622183
epcho= 600 cost= 0.0002514346851967275
epcho= 700 cost= 0.00015537298168055713
epcho= 800 cost= 9.601024794392288e-05
epcho= 900 cost= 5.9327696362743154e-05
epcho= 1000 cost= 3.66610438504722e-05
epcho= 1100 cost= 2.2655576685792767e-05
epcho= 1200 cost= 1.3999051589053124e-05
epcho= 1300 cost= 8.65114816406276e-06
epcho= 1400 cost= 5.346103989722906e-06
epcho= 1500 cost= 3.3032331430149497e-06
epcho= 1600 cost= 2.04174443751981e-06
epcho= 1700 cost= 1.2618406799447257e-06
epcho= 1800 cost= 7.801028800713539e-07
epcho= 1900 cost= 4.823282324650791e-07


In [38]:
x_train = torch.FloatTensor([[73,80,75],[93,88,93],[89,91,80],[96,98,100],[73,66,70]])
y_train = torch.FloatTensor([[152],[185],[180],[196],[142]])

In [41]:
class MulLineaRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear=nn.Linear(3,1)
    def forward(self,x):
        return self.linear(x)
    

In [42]:
model=MulLineaRegressionModel()
optimizer=torch.optim.SGD(model.parameters(), lr=1e-5)

nb_epochs=100000

for epcho in range(nb_epochs):
    prediction=model(x_train)

    cost=F.mse_loss(prediction,y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epcho % 400==0:
        print("epcho=",epcho,"cost=",cost.item())

epcho= 0 cost= 41675.6171875
epcho= 400 cost= 4.510687351226807
epcho= 800 cost= 3.7279677391052246
epcho= 1200 cost= 3.100285291671753
epcho= 1600 cost= 2.5939269065856934
epcho= 2000 cost= 2.1830406188964844
epcho= 2400 cost= 1.8477424383163452
epcho= 2800 cost= 1.5726631879806519
epcho= 3200 cost= 1.3458383083343506
epcho= 3600 cost= 1.1579153537750244
epcho= 4000 cost= 1.0015246868133545
epcho= 4400 cost= 0.8708316683769226
epcho= 4800 cost= 0.7612025737762451
epcho= 5200 cost= 0.6689440011978149
epcho= 5600 cost= 0.591052770614624
epcho= 6000 cost= 0.5251280069351196
epcho= 6400 cost= 0.46917518973350525
epcho= 6800 cost= 0.42159709334373474
epcho= 7200 cost= 0.3810548186302185
epcho= 7600 cost= 0.34645694494247437
epcho= 8000 cost= 0.31687894463539124
epcho= 8400 cost= 0.29157254099845886
epcho= 8800 cost= 0.2698829770088196
epcho= 9200 cost= 0.2512804865837097
epcho= 9600 cost= 0.23532333970069885
epcho= 10000 cost= 0.22160077095031738
epcho= 10400 cost= 0.20980671048164368
epch