In [12]:
import numpy as np

In [13]:
x_data1 =[[73., 80., 75.],
[93., 88., 93.],
[89., 91., 80.],
[96., 98., 100.],
[73., 66., 70.]]
t_data1 =[[152.], [185.], [180.], [196.], [142.]]

In [14]:
x_data=np.array(x_data1)
t_data=np.array(t_data1)
print(x_data)
print(t_data)

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  80.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]]
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]]


In [15]:
w=np.random.rand(3,1)
b=np.random.rand(1)
print(w,b)

[[0.95858127]
 [0.53846162]
 [0.19292905]] [0.32439189]


In [16]:
def loss_func(x,t):
    y=np.dot(x,w)+b # y=xw+b
    return (np.sum((t-y)**2))/len(x)

In [17]:
def mul_numerical_derivative(f,x):
    delta_x=1e-4
    grad=np.zeros_like(x) # 미분 결과값 저장 배열

    it=np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    while not it.finished:
        idx=it.multi_index

        tmp_val=x[idx]
        x[idx]=float(tmp_val)+delta_x
        fx1=f(x)
        x[idx]=tmp_val-delta_x
        fx2=f(x)
        grad[idx]=(fx1-fx2)/(2*delta_x)
        x[idx]=tmp_val
        it.iternext()
    return grad

In [18]:
def predict(x):
    y=np.dot(x,w)+b
    return y

In [20]:
learning_rate=1e-6

f=lambda x:loss_func(x_data, t_data)
print("Initial error value=",loss_func(x_data,t_data), 'w=',w,'b=',b)

for step in range(100000):
    w-=learning_rate*mul_numerical_derivative(f,w)
    b-=learning_rate*mul_numerical_derivative(f,b)
    if step%400==0:
        print("step=", step, "error value=", loss_func(x_data, t_data), 'w=',w,'b=',b)

Initial error value= 0.48790139838215546 w= [[1.08825311]
 [0.65646874]
 [0.27360037]] b= [0.32533378]
step= 0 error value= 0.4878856767159167 w= [[1.08825541]
 [0.65646954]
 [0.27359724]] b= [0.32533374]
step= 400 error value= 0.48165927870096514 w= [[1.08917284]
 [0.65678261]
 [0.27235199]] b= [0.32531812]
step= 800 error value= 0.475555256208691 w= [[1.09008443]
 [0.65708811]
 [0.27112031]] b= [0.32530237]
step= 1200 error value= 0.46957088817317255 w= [[1.09099024]
 [0.65738615]
 [0.26990204]] b= [0.32528648]
step= 1600 error value= 0.4637035210274287 w= [[1.09189027]
 [0.65767689]
 [0.268697  ]] b= [0.32527047]
step= 2000 error value= 0.45795056689168706 w= [[1.09278456]
 [0.65796044]
 [0.26750504]] b= [0.32525432]
step= 2400 error value= 0.4523095018126064 w= [[1.09367314]
 [0.65823694]
 [0.266326  ]] b= [0.32523805]
step= 2800 error value= 0.4467778640520267 w= [[1.09455604]
 [0.65850651]
 [0.26515972]] b= [0.32522165]
step= 3200 error value= 0.44135325242405027 w= [[1.09543328]