In [2]:
import torch
import torch.optim as optim

In [4]:
x_train = torch.FloatTensor([[1],[2],[3],[4],[5]])
y_train = torch.FloatTensor([[2],[4],[6],[8],[10]]) #y=2x
print(x_train)
print(y_train)
print(x_train.size())
print(y_train.size())

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.]])
tensor([[ 2.],
        [ 4.],
        [ 6.],
        [ 8.],
        [10.]])
torch.Size([5, 1])
torch.Size([5, 1])


In [5]:
w=torch.zeros(1, requires_grad=True)
b=torch.zeros(1, requires_grad=True)
print(w,b)

tensor([0.], requires_grad=True) tensor([0.], requires_grad=True)


In [6]:
h = x_train * w + b
print(h)

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [7]:
optimizer=optim.SGD([w,b], lr=0.01)

nb_epochs=2000

for epoch in range(nb_epochs):
    h = x_train * w + b
    cost=torch.mean((h - y_train)**2)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    if epoch % 100 == 0:
        print("epoch=",epoch,"w=",w.item(),"b=",b.item(), "cost value=", cost.item())

epoch= 0 w= 0.4399999976158142 b= 0.11999999731779099 cost value= 44.0
epoch= 100 w= 1.8987760543823242 b= 0.3654506504535675 cost value= 0.024474430829286575
epoch= 200 w= 1.9278557300567627 b= 0.2604633867740631 cost value= 0.012432218529284
epoch= 300 w= 1.9485814571380615 b= 0.18563701212406158 cost value= 0.006315155886113644
epoch= 400 w= 1.963353157043457 b= 0.13230684399604797 cost value= 0.003207895439118147
epoch= 500 w= 1.9738811254501343 b= 0.09429743140935898 cost value= 0.0016295012319460511
epoch= 600 w= 1.9813846349716187 b= 0.06720750033855438 cost value= 0.0008277297019958496
epoch= 700 w= 1.9867326021194458 b= 0.047899939119815826 cost value= 0.00042046388261951506
epoch= 800 w= 1.990544080734253 b= 0.03413914889097214 cost value= 0.00021357598598115146
epoch= 900 w= 1.9932606220245361 b= 0.024331560358405113 cost value= 0.0001084920804714784
epoch= 1000 w= 1.9951967000961304 b= 0.01734166033565998 cost value= 5.511019844561815e-05
epoch= 1100 w= 1.9965765476226807 b